{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "mvp",
    "description": "TODO: Add Description"
  },
  "host": "localhost:3000",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/users/1234": {
      "put": {
        "description": "TODO: Add Description",
        "summary": "update_a_user",
        "tags": [
          "Misc"
        ],
        "operationId": "Users1234Put",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateAUserrequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "PUT",
              "uri": "/users/1234",
              "headers": {
                "Content-Type": "application/json"
              },
              "body": "{\"_id\":\"1234\",\"name\":\"username\",\"address\":\"0x12233344de\",\"publicKey\":\"qqqqqqqqwwwwwweeeeeeeee\",\"cipherKey\":\"mckvdmklmdkl\",\"email\":\"userEmail\",\"invitationID\":\"002\"}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "NONE",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {}
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "update_a_user",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/users/5b2a81c0dff4b5de799d8b6b": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "http_read_a_user",
        "tags": [
          "Misc"
        ],
        "operationId": "Users5b2a81c0dff4b5de799d8b6bGet",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "GET",
              "uri": "/users/5b2a81c0dff4b5de799d8b6b"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "NONE",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {}
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "http_read_a_user",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/generateKey": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "generateKeypair",
        "tags": [
          "Misc"
        ],
        "operationId": "GenerateKeyGet",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "GET",
              "uri": "/generateKey"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "NONE",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {}
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "generateKeypair",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/sign": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "sign",
        "tags": [
          "Misc"
        ],
        "operationId": "SignPost",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/SignRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "POST",
              "uri": "/sign",
              "headers": {
                "Content-Type": "application/json"
              },
              "body": "{\"message\":{\"expirationDate\":1561050357,\"pass\":\"invitation message\",\"enabled\":\"true\",\"invitationSender\":\"0x12233344de\"},\"privateKey\":\"-----BEGIN PRIVATE KEY-----\\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDAHuE3YiIh2R+236gm83NKnAfZHDOwRuSdqoIfz8FFlYigf/V3q8gWLRS+Lp4C5HU+E0HCXPrNEn8j3OnEVF5LcUSoK91IfuNXXWWLN7hz+YokwxNjHkSeyNXOexfWnIAvejYuu/gXDENDV4TJF9bqh6V0e02rhbprshVOEpuVwUFIOpgRl37SK9gjVqGWdKD/A45evGYJP6mcxUnL4qJiaDu5Xt3GcDzeCRE3N/U0KPsOd2CgLBfhF14czHvD6oCKDRsh6XD1VCZ+cNbQu72EFeISCRAW4VzeoDvrXqbyPhlLpImm0PJQ2kwuACcHwHr6qMaBL5fzq3T+KYSzYKQtAgMBAAECggEATVRgnJVAXdVyQX6WxU7aih5xvj7uwzZV0OyPwdQy3BpLSycWG5wmRl7Q6ZgD+/APDPRdVKluPdsDF+FUqrS227D0zKgTQpnoUgMC212LPgskQpXOmOfXAP6fqKO9PaHyqqmLY5Y/Tq+d514z0WlqFS6SN2dmJPMHzU956dntjAHx+9LtU9qJLzRdrrI33NywpT03L3rRSOgYcGnALETz3nj4u8rGtsvN/QN8y0iTAbXi/+AXgNs43/BQpWehbhEIIj+oXPB92GyPSvAkzYZfQ0ffdUzbkWnAzSaN0z6t/03Ano7QJFBJNx/7GUe+6yKDP0zViaCo3y3UFv0IT5TeYQKBgQDi6HSM9FnBSX4ojUmeO16yDsSZuzAJJ4I4CQq2WrmIgXcbMxLuppbvM+q0iW1PI5ERIJ+h8rp5yBic0YEaMb6Css+uFdEF/18AicXJSYRp8T+X5OG7Mhrza+rJOrJlTjHzI5qwLwca5BDDfUXj+PvsFdOPVb/O7PP1J68WfO6gSQKBgQDYwKMQ9WUhnvIEh9qVBby+CYcqAgX+dTVy0Hf3i7Of3gC/5bVLALsG3t5hgRuNymaCkRWeRijTRxwnkxZJ05isJNwt1bYy4NEeFJUpXUzEJEKxlAK1F/bTltX88fEUaExRNBFuh91uHYluq2a2XDn4tLdbEpJC3Ef19JJArBzsxQKBgAynmDBwRD0yYxXR42QuvXZCupY0SVaJXIrRfkZzQtupFMJwk8K5ibtnctSEwZLjUejZn+2BQwMdtLmyOXgDhDN303tK/jBOcLbv+BbkwbzC1qAbBLfS8IvY3exBGMfrl3+O4canqMbIJ2MvrmErdqlRAk6BIsRglK58exhO+WP5AoGANcOSryIvc6d5YKZSEaTarEiwvjrCQdvQ5inPmBeO9pialv7jeTc1LP8bKhRcQU9zHe/e7ON6PO3mjepuHOHffNOnyba4+uXI+S0h0qDR6dUUtfeAtGq9Tr6bVaKtqeI1C+9eY4xP4IBzFoBtec5mkspAsNZqcSsyrk979465ngECgYAi+VDDSKk6ZxkXyOb1cvTsaj3vQjEoFwJoWHpu51IlUGcXbheOa6Y5aWEaue4yXPsrresiAO2QIpb5WY/oVl8EFAs5nO2SW/sfsUxbrWpEF0pSIl0Wf5OtdMdS8vrKYMwDdeVgpP8ao/E46hSoaEYZuuspmTDKazGSyHhtyMOkPQ==\\n-----END PRIVATE KEY-----\"}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "NONE",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {}
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "sign",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/verify": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "httpVerify",
        "tags": [
          "Misc"
        ],
        "operationId": "VerifyPost",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/HttpVerifyRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "POST",
              "uri": "/verify",
              "headers": {
                "Content-Type": "application/json"
              },
              "body": "{\"message\":{\"name\":\"alicia\",\"address\":\"0x12233344de\",\"publicKey\":\"-----BEGIN CERTIFICATE-----\\nMIIDPjCCAiYCCQDjPaj4hdeMFTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJlczELMAkGA1UECAwCbWExCzAJBgNVBAcMAm1hMQswCQYDVQQKDAJhbDELMAkGA1UECwwCYWwxCzAJBgNVBAMMAmFsMREwDwYJKoZIhvcNAQkBFgJhbDAeFw0xODA2MTkxNzE2NTFaFw0xOTA2MTkxNzE2NTFaMGExCzAJBgNVBAYTAmVzMQswCQYDVQQIDAJtYTELMAkGA1UEBwwCbWExCzAJBgNVBAoMAmFsMQswCQYDVQQLDAJhbDELMAkGA1UEAwwCYWwxETAPBgkqhkiG9w0BCQEWAmFsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwB7hN2IiIdkftt+oJvNzSpwH2RwzsEbknaqCH8/BRZWIoH/1d6vIFi0Uvi6eAuR1PhNBwlz6zRJ/I9zpxFReS3FEqCvdSH7jV11lize4c/mKJMMTYx5EnsjVznsX1pyAL3o2Lrv4FwxDQ1eEyRfW6oeldHtNq4W6a7IVThKblcFBSDqYEZd+0ivYI1ahlnSg/wOOXrxmCT+pnMVJy+KiYmg7uV7dxnA83gkRNzf1NCj7DndgoCwX4RdeHMx7w+qAig0bIelw9VQmfnDW0Lu9hBXiEgkQFuFc3qA7616m8j4ZS6SJptDyUNpMLgAnB8B6+qjGgS+X86t0/imEs2CkLQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBWJoeQ9uhuewNZm4jweOGzJ/QYx2h5jpBrka0f1Bd5mTxcqB9J/IjkeCjK9Qo2wffQVLxa9jW9/Q8eqUdvqhbRluyQupvJeifs2B710nZgAEp5VcpaSJNhj4YQIaw640f5FLHu4Rt8POezHwvSuGedalFXsQO/PJV3IKg6OpNZyLhT2c0H2NqOHJmnV3ltU4jR2aVU/lWLCvH0Lzlb3R/NAUvqgvDTugUkt2WoV+7sw57rEhNI4r5v4FEd1cbSOFu2Xnfk2Upgz5wswdkF8faZQR4LyDj4ZlCD5RSjaHaMLXJe7CZU33zHwaUbig+fPW4JYrDq7HZHT7i2+KsNLMil\\n-----END CERTIFICATE-----\",\"cipherKey\":\"mckvdmklmdkl\",\"email\":\"userEmail@mail\",\"invitationID\":2},\"publicKey\":\"-----BEGIN CERTIFICATE-----\\nMIIDPjCCAiYCCQDjPaj4hdeMFTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJlczELMAkGA1UECAwCbWExCzAJBgNVBAcMAm1hMQswCQYDVQQKDAJhbDELMAkGA1UECwwCYWwxCzAJBgNVBAMMAmFsMREwDwYJKoZIhvcNAQkBFgJhbDAeFw0xODA2MTkxNzE2NTFaFw0xOTA2MTkxNzE2NTFaMGExCzAJBgNVBAYTAmVzMQswCQYDVQQIDAJtYTELMAkGA1UEBwwCbWExCzAJBgNVBAoMAmFsMQswCQYDVQQLDAJhbDELMAkGA1UEAwwCYWwxETAPBgkqhkiG9w0BCQEWAmFsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwB7hN2IiIdkftt+oJvNzSpwH2RwzsEbknaqCH8/BRZWIoH/1d6vIFi0Uvi6eAuR1PhNBwlz6zRJ/I9zpxFReS3FEqCvdSH7jV11lize4c/mKJMMTYx5EnsjVznsX1pyAL3o2Lrv4FwxDQ1eEyRfW6oeldHtNq4W6a7IVThKblcFBSDqYEZd+0ivYI1ahlnSg/wOOXrxmCT+pnMVJy+KiYmg7uV7dxnA83gkRNzf1NCj7DndgoCwX4RdeHMx7w+qAig0bIelw9VQmfnDW0Lu9hBXiEgkQFuFc3qA7616m8j4ZS6SJptDyUNpMLgAnB8B6+qjGgS+X86t0/imEs2CkLQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBWJoeQ9uhuewNZm4jweOGzJ/QYx2h5jpBrka0f1Bd5mTxcqB9J/IjkeCjK9Qo2wffQVLxa9jW9/Q8eqUdvqhbRluyQupvJeifs2B710nZgAEp5VcpaSJNhj4YQIaw640f5FLHu4Rt8POezHwvSuGedalFXsQO/PJV3IKg6OpNZyLhT2c0H2NqOHJmnV3ltU4jR2aVU/lWLCvH0Lzlb3R/NAUvqgvDTugUkt2WoV+7sw57rEhNI4r5v4FEd1cbSOFu2Xnfk2Upgz5wswdkF8faZQR4LyDj4ZlCD5RSjaHaMLXJe7CZU33zHwaUbig+fPW4JYrDq7HZHT7i2+KsNLMil\\n-----END CERTIFICATE-----\",\"signature\":\"4269085c8eaae289c297e735d2926b113b94ae755545c36b0e76cf9035ce1c0c39873f1da38d928abee49fd3bcc52be399764fb6408696b1f7556c234d4f44a842b1b92c1fc2681ccadf863278645c18ed20c6cd49d183c7f14b58c7a938067776fb0a3d9e698b0c3204d751561d6ebf2eb7f251e64474e5c2dc9ef7609cfba4d4a019d622d03a24aa4e32698778eaa61d75033ea263f14cf6e947636950b000b4471f72ce7a9d875adbf28d4493d46c8c76becbca65b80be75fe7b3a42f9cfd3eb0ace68155e6caeb60b471a3797af80457f907c4b1f2b6dadd178324d5dccf10be0d4ee3bd21a1969f57c3cf805086b727c31706cdfb676ecd8b9ac364b172\"}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "NONE",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {}
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "httpVerify",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/users": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "list_all_users",
        "tags": [
          "Misc"
        ],
        "operationId": "UsersGet",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "GET",
              "uri": "/users"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "NONE",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {}
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "list_all_users",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "description": "TODO: Add Description",
        "summary": "create_a_user",
        "tags": [
          "Misc"
        ],
        "operationId": "UsersPost",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/CreateAUserrequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "POST",
              "uri": "/users",
              "headers": {
                "Content-Type": "application/json"
              },
              "body": "{\"sender\":\"alicia\",\"message\":{\"name\":\"bob\",\"address\":\"0xb12233344de2\",\"publicKey\":\"-----BEGIN CERTIFICATE-----\\nMIIDPjCCAiYCCQDjPaj4hdeMFTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJlczELMAkGA1UECAwCbWExCzAJBgNVBAcMAm1hMQswCQYDVQQKDAJhbDELMAkGA1UECwwCYWwxCzAJBgNVBAMMAmFsMREwDwYJKoZIhvcNAQkBFgJhbDAeFw0xODA2MTkxNzE2NTFaFw0xOTA2MTkxNzE2NTFaMGExCzAJBgNVBAYTAmVzMQswCQYDVQQIDAJtYTELMAkGA1UEBwwCbWExCzAJBgNVBAoMAmFsMQswCQYDVQQLDAJhbDELMAkGA1UEAwwCYWwxETAPBgkqhkiG9w0BCQEWAmFsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwB7hN2IiIdkftt+oJvNzSpwH2RwzsEbknaqCH8/BRZWIoH/1d6vIFi0Uvi6eAuR1PhNBwlz6zRJ/I9zpxFReS3FEqCvdSH7jV11lize4c/mKJMMTYx5EnsjVznsX1pyAL3o2Lrv4FwxDQ1eEyRfW6oeldHtNq4W6a7IVThKblcFBSDqYEZd+0ivYI1ahlnSg/wOOXrxmCT+pnMVJy+KiYmg7uV7dxnA83gkRNzf1NCj7DndgoCwX4RdeHMx7w+qAig0bIelw9VQmfnDW0Lu9hBXiEgkQFuFc3qA7616m8j4ZS6SJptDyUNpMLgAnB8B6+qjGgS+X86t0/imEs2CkLQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBWJoeQ9uhuewNZm4jweOGzJ/QYx2h5jpBrka0f1Bd5mTxcqB9J/IjkeCjK9Qo2wffQVLxa9jW9/Q8eqUdvqhbRluyQupvJeifs2B710nZgAEp5VcpaSJNhj4YQIaw640f5FLHu4Rt8POezHwvSuGedalFXsQO/PJV3IKg6OpNZyLhT2c0H2NqOHJmnV3ltU4jR2aVU/lWLCvH0Lzlb3R/NAUvqgvDTugUkt2WoV+7sw57rEhNI4r5v4FEd1cbSOFu2Xnfk2Upgz5wswdkF8faZQR4LyDj4ZlCD5RSjaHaMLXJe7CZU33zHwaUbig+fPW4JYrDq7HZHT7i2+KsNLMil\\n-----END CERTIFICATE-----\",\"cipherKey\":\"bobcipherKey\",\"email\":\"bob@mail.com\",\"invitationID\":\"0x12233344de\"},\"pass\":\"invitation message\",\"signature\":\"337aa3432103290b30f579ba62c72a370277bcb23fb798609cfdcf0909698c431788324f8ecf55e6f8d16cf8b1e5ae8606a3de77d3506a7c08e02894d4c0ba8126e8b09c38d7fdb85de2586b2b43cc76580358ae985e129f1296c821e5ac4a22258ec5d90048cd02fc063440682d5572f918f6b2dbaf7dd55bab5d26edfb81ec33a1904c1288205f4d7a70d3737c62cdb0f0eaee7218a17a46e1f5d25af97bd1ce24a5138804dbd4c48453274c7e028e687f58ba95b76bb7d6d2d881a1563d6cd32f46939fed24c1dde760d7b4a70ec406fdcc2e34bb5bbc8415831423468cebed80dc1b5ba3c89740ef2fc18477c49e9d408869c0d1a8a21a4abf1c437f8473\"}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "NONE",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {}
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "create_a_user",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/invitations": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "create_a_invitation",
        "tags": [
          "Misc"
        ],
        "operationId": "InvitationsPost",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/CreateAInvitationrequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "POST",
              "uri": "/invitations",
              "headers": {
                "Content-Type": "application/json"
              },
              "body": "{\"address\":\"0x12233344de\",\"message\":{\"expirationDate\":1561050357,\"pass\":\"invitation message\",\"enabled\":\"true\",\"invitationSender\":\"0x12233344de\"},\"signature\":\"828773912f75628279a0d2f7f197c7cd960d0286a7b663dc6837dede73e1e58b29a0317d14535a64976ea8ae8b8684598f597ff472667417105efc299488e623b200c8963471375572bdf51d4489df87443bfa018cb4d64a833ca67a5e431170bd4913e19c5645d595f0db0ee7a0813c7847871569d9a3680dfb0eb292581cad481e43c25be10997d9a45d300b7366e804807dd7962ee199a0c991fd227f34a6b0e9ba50ee6d543f88799900bcb6990e37d31ddb95605a79bba8b4f0c31f67a9052062c4296bdebf16cb14d18c116d04830512d535bbff315d72537916a25531552d18f9b99787aa2036b1e96046c4c05c4317b4690ede2bfcdf49fc22c96560\"}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "NONE",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {}
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "create_a_invitation",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/invitations/5b2bba6a042ab5cb4c7aebfa": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "http_read_a_invitation",
        "tags": [
          "Misc"
        ],
        "operationId": "Invitations5b2bba6a042ab5cb4c7aebfaGet",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "GET",
              "uri": "/invitations/5b2bba6a042ab5cb4c7aebfa"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "NONE",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {}
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "http_read_a_invitation",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "put": {
        "description": "TODO: Add Description",
        "summary": "update_a_invitation",
        "tags": [
          "Misc"
        ],
        "operationId": "Invitations5b2bba6a042ab5cb4c7aebfaPut",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateAInvitationrequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "security": [],
        "x-unitTests": [
          {
            "request": {
              "method": "PUT",
              "uri": "/invitations/5b2bba6a042ab5cb4c7aebfa",
              "headers": {
                "Content-Type": "application/json"
              },
              "body": "{\"enabled\":true,\"_id\":\"5b2bba6a042ab5cb4c7aebfa\",\"expirationDate\":1561050357,\"pass\":\"invitation message\",\"invitationSender\":\"0x12233344de\",\"__v\":0}"
            },
            "expectedResponse": {
              "x-allowExtraHeaders": true,
              "x-bodyMatchMode": "NONE",
              "x-arrayOrderedMatching": false,
              "x-arrayCheckCount": false,
              "x-matchResponseSchema": true,
              "headers": {}
            },
            "x-testShouldPass": true,
            "x-testEnabled": true,
            "x-testName": "update_a_invitation",
            "x-testDescription": "TODO: Add Description"
          }
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    }
  },
  "definitions": {
    "UpdateAUserrequest": {
      "title": "update_a_userRequest",
      "example": {
        "_id": "1234",
        "name": "username",
        "address": "0x12233344de",
        "publicKey": "qqqqqqqqwwwwwweeeeeeeee",
        "cipherKey": "mckvdmklmdkl",
        "email": "userEmail",
        "invitationID": "002"
      },
      "type": "object",
      "properties": {
        "_id": {
          "description": "",
          "example": "1234",
          "type": "string"
        },
        "name": {
          "description": "",
          "example": "username",
          "type": "string"
        },
        "address": {
          "description": "",
          "example": "0x12233344de",
          "type": "string"
        },
        "publicKey": {
          "description": "",
          "example": "qqqqqqqqwwwwwweeeeeeeee",
          "type": "string"
        },
        "cipherKey": {
          "description": "",
          "example": "mckvdmklmdkl",
          "type": "string"
        },
        "email": {
          "description": "",
          "example": "userEmail",
          "type": "string"
        },
        "invitationID": {
          "description": "",
          "example": "002",
          "type": "string"
        }
      },
      "required": [
        "_id",
        "name",
        "address",
        "publicKey",
        "cipherKey",
        "email",
        "invitationID"
      ]
    },
    "SignRequest": {
      "title": "signRequest",
      "example": {
        "message": {
          "expirationDate": 1561050357,
          "pass": "invitation message",
          "enabled": "true",
          "invitationSender": "0x12233344de"
        },
        "privateKey": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDAHuE3YiIh2R+236gm83NKnAfZHDOwRuSdqoIfz8FFlYigf/V3q8gWLRS+Lp4C5HU+E0HCXPrNEn8j3OnEVF5LcUSoK91IfuNXXWWLN7hz+YokwxNjHkSeyNXOexfWnIAvejYuu/gXDENDV4TJF9bqh6V0e02rhbprshVOEpuVwUFIOpgRl37SK9gjVqGWdKD/A45evGYJP6mcxUnL4qJiaDu5Xt3GcDzeCRE3N/U0KPsOd2CgLBfhF14czHvD6oCKDRsh6XD1VCZ+cNbQu72EFeISCRAW4VzeoDvrXqbyPhlLpImm0PJQ2kwuACcHwHr6qMaBL5fzq3T+KYSzYKQtAgMBAAECggEATVRgnJVAXdVyQX6WxU7aih5xvj7uwzZV0OyPwdQy3BpLSycWG5wmRl7Q6ZgD+/APDPRdVKluPdsDF+FUqrS227D0zKgTQpnoUgMC212LPgskQpXOmOfXAP6fqKO9PaHyqqmLY5Y/Tq+d514z0WlqFS6SN2dmJPMHzU956dntjAHx+9LtU9qJLzRdrrI33NywpT03L3rRSOgYcGnALETz3nj4u8rGtsvN/QN8y0iTAbXi/+AXgNs43/BQpWehbhEIIj+oXPB92GyPSvAkzYZfQ0ffdUzbkWnAzSaN0z6t/03Ano7QJFBJNx/7GUe+6yKDP0zViaCo3y3UFv0IT5TeYQKBgQDi6HSM9FnBSX4ojUmeO16yDsSZuzAJJ4I4CQq2WrmIgXcbMxLuppbvM+q0iW1PI5ERIJ+h8rp5yBic0YEaMb6Css+uFdEF/18AicXJSYRp8T+X5OG7Mhrza+rJOrJlTjHzI5qwLwca5BDDfUXj+PvsFdOPVb/O7PP1J68WfO6gSQKBgQDYwKMQ9WUhnvIEh9qVBby+CYcqAgX+dTVy0Hf3i7Of3gC/5bVLALsG3t5hgRuNymaCkRWeRijTRxwnkxZJ05isJNwt1bYy4NEeFJUpXUzEJEKxlAK1F/bTltX88fEUaExRNBFuh91uHYluq2a2XDn4tLdbEpJC3Ef19JJArBzsxQKBgAynmDBwRD0yYxXR42QuvXZCupY0SVaJXIrRfkZzQtupFMJwk8K5ibtnctSEwZLjUejZn+2BQwMdtLmyOXgDhDN303tK/jBOcLbv+BbkwbzC1qAbBLfS8IvY3exBGMfrl3+O4canqMbIJ2MvrmErdqlRAk6BIsRglK58exhO+WP5AoGANcOSryIvc6d5YKZSEaTarEiwvjrCQdvQ5inPmBeO9pialv7jeTc1LP8bKhRcQU9zHe/e7ON6PO3mjepuHOHffNOnyba4+uXI+S0h0qDR6dUUtfeAtGq9Tr6bVaKtqeI1C+9eY4xP4IBzFoBtec5mkspAsNZqcSsyrk979465ngECgYAi+VDDSKk6ZxkXyOb1cvTsaj3vQjEoFwJoWHpu51IlUGcXbheOa6Y5aWEaue4yXPsrresiAO2QIpb5WY/oVl8EFAs5nO2SW/sfsUxbrWpEF0pSIl0Wf5OtdMdS8vrKYMwDdeVgpP8ao/E46hSoaEYZuuspmTDKazGSyHhtyMOkPQ==\n-----END PRIVATE KEY-----"
      },
      "type": "object",
      "properties": {
        "message": {
          "$ref": "#/definitions/Message"
        },
        "privateKey": {
          "description": "",
          "example": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDAHuE3YiIh2R+236gm83NKnAfZHDOwRuSdqoIfz8FFlYigf/V3q8gWLRS+Lp4C5HU+E0HCXPrNEn8j3OnEVF5LcUSoK91IfuNXXWWLN7hz+YokwxNjHkSeyNXOexfWnIAvejYuu/gXDENDV4TJF9bqh6V0e02rhbprshVOEpuVwUFIOpgRl37SK9gjVqGWdKD/A45evGYJP6mcxUnL4qJiaDu5Xt3GcDzeCRE3N/U0KPsOd2CgLBfhF14czHvD6oCKDRsh6XD1VCZ+cNbQu72EFeISCRAW4VzeoDvrXqbyPhlLpImm0PJQ2kwuACcHwHr6qMaBL5fzq3T+KYSzYKQtAgMBAAECggEATVRgnJVAXdVyQX6WxU7aih5xvj7uwzZV0OyPwdQy3BpLSycWG5wmRl7Q6ZgD+/APDPRdVKluPdsDF+FUqrS227D0zKgTQpnoUgMC212LPgskQpXOmOfXAP6fqKO9PaHyqqmLY5Y/Tq+d514z0WlqFS6SN2dmJPMHzU956dntjAHx+9LtU9qJLzRdrrI33NywpT03L3rRSOgYcGnALETz3nj4u8rGtsvN/QN8y0iTAbXi/+AXgNs43/BQpWehbhEIIj+oXPB92GyPSvAkzYZfQ0ffdUzbkWnAzSaN0z6t/03Ano7QJFBJNx/7GUe+6yKDP0zViaCo3y3UFv0IT5TeYQKBgQDi6HSM9FnBSX4ojUmeO16yDsSZuzAJJ4I4CQq2WrmIgXcbMxLuppbvM+q0iW1PI5ERIJ+h8rp5yBic0YEaMb6Css+uFdEF/18AicXJSYRp8T+X5OG7Mhrza+rJOrJlTjHzI5qwLwca5BDDfUXj+PvsFdOPVb/O7PP1J68WfO6gSQKBgQDYwKMQ9WUhnvIEh9qVBby+CYcqAgX+dTVy0Hf3i7Of3gC/5bVLALsG3t5hgRuNymaCkRWeRijTRxwnkxZJ05isJNwt1bYy4NEeFJUpXUzEJEKxlAK1F/bTltX88fEUaExRNBFuh91uHYluq2a2XDn4tLdbEpJC3Ef19JJArBzsxQKBgAynmDBwRD0yYxXR42QuvXZCupY0SVaJXIrRfkZzQtupFMJwk8K5ibtnctSEwZLjUejZn+2BQwMdtLmyOXgDhDN303tK/jBOcLbv+BbkwbzC1qAbBLfS8IvY3exBGMfrl3+O4canqMbIJ2MvrmErdqlRAk6BIsRglK58exhO+WP5AoGANcOSryIvc6d5YKZSEaTarEiwvjrCQdvQ5inPmBeO9pialv7jeTc1LP8bKhRcQU9zHe/e7ON6PO3mjepuHOHffNOnyba4+uXI+S0h0qDR6dUUtfeAtGq9Tr6bVaKtqeI1C+9eY4xP4IBzFoBtec5mkspAsNZqcSsyrk979465ngECgYAi+VDDSKk6ZxkXyOb1cvTsaj3vQjEoFwJoWHpu51IlUGcXbheOa6Y5aWEaue4yXPsrresiAO2QIpb5WY/oVl8EFAs5nO2SW/sfsUxbrWpEF0pSIl0Wf5OtdMdS8vrKYMwDdeVgpP8ao/E46hSoaEYZuuspmTDKazGSyHhtyMOkPQ==\n-----END PRIVATE KEY-----",
          "type": "string"
        }
      },
      "required": [
        "message",
        "privateKey"
      ]
    },
    "Message": {
      "title": "Message",
      "example": {
        "expirationDate": 1561050357,
        "pass": "invitation message",
        "enabled": "true",
        "invitationSender": "0x12233344de"
      },
      "type": "object",
      "properties": {
        "expirationDate": {
          "description": "",
          "example": 1561050357,
          "type": "integer",
          "format": "int32"
        },
        "pass": {
          "description": "",
          "example": "invitation message",
          "type": "string"
        },
        "enabled": {
          "description": "",
          "example": "true",
          "type": "string"
        },
        "invitationSender": {
          "description": "",
          "example": "0x12233344de",
          "type": "string"
        }
      },
      "required": [
        "expirationDate",
        "pass",
        "enabled",
        "invitationSender"
      ]
    },
    "HttpVerifyRequest": {
      "title": "httpVerifyRequest",
      "example": {
        "message": {
          "name": "alicia",
          "address": "0x12233344de",
          "publicKey": "-----BEGIN CERTIFICATE-----\nMIIDPjCCAiYCCQDjPaj4hdeMFTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJlczELMAkGA1UECAwCbWExCzAJBgNVBAcMAm1hMQswCQYDVQQKDAJhbDELMAkGA1UECwwCYWwxCzAJBgNVBAMMAmFsMREwDwYJKoZIhvcNAQkBFgJhbDAeFw0xODA2MTkxNzE2NTFaFw0xOTA2MTkxNzE2NTFaMGExCzAJBgNVBAYTAmVzMQswCQYDVQQIDAJtYTELMAkGA1UEBwwCbWExCzAJBgNVBAoMAmFsMQswCQYDVQQLDAJhbDELMAkGA1UEAwwCYWwxETAPBgkqhkiG9w0BCQEWAmFsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwB7hN2IiIdkftt+oJvNzSpwH2RwzsEbknaqCH8/BRZWIoH/1d6vIFi0Uvi6eAuR1PhNBwlz6zRJ/I9zpxFReS3FEqCvdSH7jV11lize4c/mKJMMTYx5EnsjVznsX1pyAL3o2Lrv4FwxDQ1eEyRfW6oeldHtNq4W6a7IVThKblcFBSDqYEZd+0ivYI1ahlnSg/wOOXrxmCT+pnMVJy+KiYmg7uV7dxnA83gkRNzf1NCj7DndgoCwX4RdeHMx7w+qAig0bIelw9VQmfnDW0Lu9hBXiEgkQFuFc3qA7616m8j4ZS6SJptDyUNpMLgAnB8B6+qjGgS+X86t0/imEs2CkLQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBWJoeQ9uhuewNZm4jweOGzJ/QYx2h5jpBrka0f1Bd5mTxcqB9J/IjkeCjK9Qo2wffQVLxa9jW9/Q8eqUdvqhbRluyQupvJeifs2B710nZgAEp5VcpaSJNhj4YQIaw640f5FLHu4Rt8POezHwvSuGedalFXsQO/PJV3IKg6OpNZyLhT2c0H2NqOHJmnV3ltU4jR2aVU/lWLCvH0Lzlb3R/NAUvqgvDTugUkt2WoV+7sw57rEhNI4r5v4FEd1cbSOFu2Xnfk2Upgz5wswdkF8faZQR4LyDj4ZlCD5RSjaHaMLXJe7CZU33zHwaUbig+fPW4JYrDq7HZHT7i2+KsNLMil\n-----END CERTIFICATE-----",
          "cipherKey": "mckvdmklmdkl",
          "email": "userEmail@mail",
          "invitationID": 2
        },
        "publicKey": "-----BEGIN CERTIFICATE-----\nMIIDPjCCAiYCCQDjPaj4hdeMFTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJlczELMAkGA1UECAwCbWExCzAJBgNVBAcMAm1hMQswCQYDVQQKDAJhbDELMAkGA1UECwwCYWwxCzAJBgNVBAMMAmFsMREwDwYJKoZIhvcNAQkBFgJhbDAeFw0xODA2MTkxNzE2NTFaFw0xOTA2MTkxNzE2NTFaMGExCzAJBgNVBAYTAmVzMQswCQYDVQQIDAJtYTELMAkGA1UEBwwCbWExCzAJBgNVBAoMAmFsMQswCQYDVQQLDAJhbDELMAkGA1UEAwwCYWwxETAPBgkqhkiG9w0BCQEWAmFsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwB7hN2IiIdkftt+oJvNzSpwH2RwzsEbknaqCH8/BRZWIoH/1d6vIFi0Uvi6eAuR1PhNBwlz6zRJ/I9zpxFReS3FEqCvdSH7jV11lize4c/mKJMMTYx5EnsjVznsX1pyAL3o2Lrv4FwxDQ1eEyRfW6oeldHtNq4W6a7IVThKblcFBSDqYEZd+0ivYI1ahlnSg/wOOXrxmCT+pnMVJy+KiYmg7uV7dxnA83gkRNzf1NCj7DndgoCwX4RdeHMx7w+qAig0bIelw9VQmfnDW0Lu9hBXiEgkQFuFc3qA7616m8j4ZS6SJptDyUNpMLgAnB8B6+qjGgS+X86t0/imEs2CkLQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBWJoeQ9uhuewNZm4jweOGzJ/QYx2h5jpBrka0f1Bd5mTxcqB9J/IjkeCjK9Qo2wffQVLxa9jW9/Q8eqUdvqhbRluyQupvJeifs2B710nZgAEp5VcpaSJNhj4YQIaw640f5FLHu4Rt8POezHwvSuGedalFXsQO/PJV3IKg6OpNZyLhT2c0H2NqOHJmnV3ltU4jR2aVU/lWLCvH0Lzlb3R/NAUvqgvDTugUkt2WoV+7sw57rEhNI4r5v4FEd1cbSOFu2Xnfk2Upgz5wswdkF8faZQR4LyDj4ZlCD5RSjaHaMLXJe7CZU33zHwaUbig+fPW4JYrDq7HZHT7i2+KsNLMil\n-----END CERTIFICATE-----",
        "signature": "4269085c8eaae289c297e735d2926b113b94ae755545c36b0e76cf9035ce1c0c39873f1da38d928abee49fd3bcc52be399764fb6408696b1f7556c234d4f44a842b1b92c1fc2681ccadf863278645c18ed20c6cd49d183c7f14b58c7a938067776fb0a3d9e698b0c3204d751561d6ebf2eb7f251e64474e5c2dc9ef7609cfba4d4a019d622d03a24aa4e32698778eaa61d75033ea263f14cf6e947636950b000b4471f72ce7a9d875adbf28d4493d46c8c76becbca65b80be75fe7b3a42f9cfd3eb0ace68155e6caeb60b471a3797af80457f907c4b1f2b6dadd178324d5dccf10be0d4ee3bd21a1969f57c3cf805086b727c31706cdfb676ecd8b9ac364b172"
      },
      "type": "object",
      "properties": {
        "message": {
          "$ref": "#/definitions/Message4"
        },
        "publicKey": {
          "description": "",
          "example": "-----BEGIN CERTIFICATE-----\nMIIDPjCCAiYCCQDjPaj4hdeMFTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJlczELMAkGA1UECAwCbWExCzAJBgNVBAcMAm1hMQswCQYDVQQKDAJhbDELMAkGA1UECwwCYWwxCzAJBgNVBAMMAmFsMREwDwYJKoZIhvcNAQkBFgJhbDAeFw0xODA2MTkxNzE2NTFaFw0xOTA2MTkxNzE2NTFaMGExCzAJBgNVBAYTAmVzMQswCQYDVQQIDAJtYTELMAkGA1UEBwwCbWExCzAJBgNVBAoMAmFsMQswCQYDVQQLDAJhbDELMAkGA1UEAwwCYWwxETAPBgkqhkiG9w0BCQEWAmFsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwB7hN2IiIdkftt+oJvNzSpwH2RwzsEbknaqCH8/BRZWIoH/1d6vIFi0Uvi6eAuR1PhNBwlz6zRJ/I9zpxFReS3FEqCvdSH7jV11lize4c/mKJMMTYx5EnsjVznsX1pyAL3o2Lrv4FwxDQ1eEyRfW6oeldHtNq4W6a7IVThKblcFBSDqYEZd+0ivYI1ahlnSg/wOOXrxmCT+pnMVJy+KiYmg7uV7dxnA83gkRNzf1NCj7DndgoCwX4RdeHMx7w+qAig0bIelw9VQmfnDW0Lu9hBXiEgkQFuFc3qA7616m8j4ZS6SJptDyUNpMLgAnB8B6+qjGgS+X86t0/imEs2CkLQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBWJoeQ9uhuewNZm4jweOGzJ/QYx2h5jpBrka0f1Bd5mTxcqB9J/IjkeCjK9Qo2wffQVLxa9jW9/Q8eqUdvqhbRluyQupvJeifs2B710nZgAEp5VcpaSJNhj4YQIaw640f5FLHu4Rt8POezHwvSuGedalFXsQO/PJV3IKg6OpNZyLhT2c0H2NqOHJmnV3ltU4jR2aVU/lWLCvH0Lzlb3R/NAUvqgvDTugUkt2WoV+7sw57rEhNI4r5v4FEd1cbSOFu2Xnfk2Upgz5wswdkF8faZQR4LyDj4ZlCD5RSjaHaMLXJe7CZU33zHwaUbig+fPW4JYrDq7HZHT7i2+KsNLMil\n-----END CERTIFICATE-----",
          "type": "string"
        },
        "signature": {
          "description": "",
          "example": "4269085c8eaae289c297e735d2926b113b94ae755545c36b0e76cf9035ce1c0c39873f1da38d928abee49fd3bcc52be399764fb6408696b1f7556c234d4f44a842b1b92c1fc2681ccadf863278645c18ed20c6cd49d183c7f14b58c7a938067776fb0a3d9e698b0c3204d751561d6ebf2eb7f251e64474e5c2dc9ef7609cfba4d4a019d622d03a24aa4e32698778eaa61d75033ea263f14cf6e947636950b000b4471f72ce7a9d875adbf28d4493d46c8c76becbca65b80be75fe7b3a42f9cfd3eb0ace68155e6caeb60b471a3797af80457f907c4b1f2b6dadd178324d5dccf10be0d4ee3bd21a1969f57c3cf805086b727c31706cdfb676ecd8b9ac364b172",
          "type": "string"
        }
      },
      "required": [
        "message",
        "publicKey",
        "signature"
      ]
    },
    "Message4": {
      "title": "Message4",
      "example": {
        "name": "alicia",
        "address": "0x12233344de",
        "publicKey": "-----BEGIN CERTIFICATE-----\nMIIDPjCCAiYCCQDjPaj4hdeMFTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJlczELMAkGA1UECAwCbWExCzAJBgNVBAcMAm1hMQswCQYDVQQKDAJhbDELMAkGA1UECwwCYWwxCzAJBgNVBAMMAmFsMREwDwYJKoZIhvcNAQkBFgJhbDAeFw0xODA2MTkxNzE2NTFaFw0xOTA2MTkxNzE2NTFaMGExCzAJBgNVBAYTAmVzMQswCQYDVQQIDAJtYTELMAkGA1UEBwwCbWExCzAJBgNVBAoMAmFsMQswCQYDVQQLDAJhbDELMAkGA1UEAwwCYWwxETAPBgkqhkiG9w0BCQEWAmFsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwB7hN2IiIdkftt+oJvNzSpwH2RwzsEbknaqCH8/BRZWIoH/1d6vIFi0Uvi6eAuR1PhNBwlz6zRJ/I9zpxFReS3FEqCvdSH7jV11lize4c/mKJMMTYx5EnsjVznsX1pyAL3o2Lrv4FwxDQ1eEyRfW6oeldHtNq4W6a7IVThKblcFBSDqYEZd+0ivYI1ahlnSg/wOOXrxmCT+pnMVJy+KiYmg7uV7dxnA83gkRNzf1NCj7DndgoCwX4RdeHMx7w+qAig0bIelw9VQmfnDW0Lu9hBXiEgkQFuFc3qA7616m8j4ZS6SJptDyUNpMLgAnB8B6+qjGgS+X86t0/imEs2CkLQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBWJoeQ9uhuewNZm4jweOGzJ/QYx2h5jpBrka0f1Bd5mTxcqB9J/IjkeCjK9Qo2wffQVLxa9jW9/Q8eqUdvqhbRluyQupvJeifs2B710nZgAEp5VcpaSJNhj4YQIaw640f5FLHu4Rt8POezHwvSuGedalFXsQO/PJV3IKg6OpNZyLhT2c0H2NqOHJmnV3ltU4jR2aVU/lWLCvH0Lzlb3R/NAUvqgvDTugUkt2WoV+7sw57rEhNI4r5v4FEd1cbSOFu2Xnfk2Upgz5wswdkF8faZQR4LyDj4ZlCD5RSjaHaMLXJe7CZU33zHwaUbig+fPW4JYrDq7HZHT7i2+KsNLMil\n-----END CERTIFICATE-----",
        "cipherKey": "mckvdmklmdkl",
        "email": "userEmail@mail",
        "invitationID": 2
      },
      "type": "object",
      "properties": {
        "name": {
          "description": "",
          "example": "alicia",
          "type": "string"
        },
        "address": {
          "description": "",
          "example": "0x12233344de",
          "type": "string"
        },
        "publicKey": {
          "description": "",
          "example": "-----BEGIN CERTIFICATE-----\nMIIDPjCCAiYCCQDjPaj4hdeMFTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJlczELMAkGA1UECAwCbWExCzAJBgNVBAcMAm1hMQswCQYDVQQKDAJhbDELMAkGA1UECwwCYWwxCzAJBgNVBAMMAmFsMREwDwYJKoZIhvcNAQkBFgJhbDAeFw0xODA2MTkxNzE2NTFaFw0xOTA2MTkxNzE2NTFaMGExCzAJBgNVBAYTAmVzMQswCQYDVQQIDAJtYTELMAkGA1UEBwwCbWExCzAJBgNVBAoMAmFsMQswCQYDVQQLDAJhbDELMAkGA1UEAwwCYWwxETAPBgkqhkiG9w0BCQEWAmFsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwB7hN2IiIdkftt+oJvNzSpwH2RwzsEbknaqCH8/BRZWIoH/1d6vIFi0Uvi6eAuR1PhNBwlz6zRJ/I9zpxFReS3FEqCvdSH7jV11lize4c/mKJMMTYx5EnsjVznsX1pyAL3o2Lrv4FwxDQ1eEyRfW6oeldHtNq4W6a7IVThKblcFBSDqYEZd+0ivYI1ahlnSg/wOOXrxmCT+pnMVJy+KiYmg7uV7dxnA83gkRNzf1NCj7DndgoCwX4RdeHMx7w+qAig0bIelw9VQmfnDW0Lu9hBXiEgkQFuFc3qA7616m8j4ZS6SJptDyUNpMLgAnB8B6+qjGgS+X86t0/imEs2CkLQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBWJoeQ9uhuewNZm4jweOGzJ/QYx2h5jpBrka0f1Bd5mTxcqB9J/IjkeCjK9Qo2wffQVLxa9jW9/Q8eqUdvqhbRluyQupvJeifs2B710nZgAEp5VcpaSJNhj4YQIaw640f5FLHu4Rt8POezHwvSuGedalFXsQO/PJV3IKg6OpNZyLhT2c0H2NqOHJmnV3ltU4jR2aVU/lWLCvH0Lzlb3R/NAUvqgvDTugUkt2WoV+7sw57rEhNI4r5v4FEd1cbSOFu2Xnfk2Upgz5wswdkF8faZQR4LyDj4ZlCD5RSjaHaMLXJe7CZU33zHwaUbig+fPW4JYrDq7HZHT7i2+KsNLMil\n-----END CERTIFICATE-----",
          "type": "string"
        },
        "cipherKey": {
          "description": "",
          "example": "mckvdmklmdkl",
          "type": "string"
        },
        "email": {
          "description": "",
          "example": "userEmail@mail",
          "type": "string"
        },
        "invitationID": {
          "description": "",
          "example": 2,
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "name",
        "address",
        "publicKey",
        "cipherKey",
        "email",
        "invitationID"
      ]
    },
    "CreateAUserrequest": {
      "title": "create_a_userRequest",
      "example": {
        "sender": "alicia",
        "message": {
          "name": "bob",
          "address": "0xb12233344de2",
          "publicKey": "-----BEGIN CERTIFICATE-----\nMIIDPjCCAiYCCQDjPaj4hdeMFTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJlczELMAkGA1UECAwCbWExCzAJBgNVBAcMAm1hMQswCQYDVQQKDAJhbDELMAkGA1UECwwCYWwxCzAJBgNVBAMMAmFsMREwDwYJKoZIhvcNAQkBFgJhbDAeFw0xODA2MTkxNzE2NTFaFw0xOTA2MTkxNzE2NTFaMGExCzAJBgNVBAYTAmVzMQswCQYDVQQIDAJtYTELMAkGA1UEBwwCbWExCzAJBgNVBAoMAmFsMQswCQYDVQQLDAJhbDELMAkGA1UEAwwCYWwxETAPBgkqhkiG9w0BCQEWAmFsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwB7hN2IiIdkftt+oJvNzSpwH2RwzsEbknaqCH8/BRZWIoH/1d6vIFi0Uvi6eAuR1PhNBwlz6zRJ/I9zpxFReS3FEqCvdSH7jV11lize4c/mKJMMTYx5EnsjVznsX1pyAL3o2Lrv4FwxDQ1eEyRfW6oeldHtNq4W6a7IVThKblcFBSDqYEZd+0ivYI1ahlnSg/wOOXrxmCT+pnMVJy+KiYmg7uV7dxnA83gkRNzf1NCj7DndgoCwX4RdeHMx7w+qAig0bIelw9VQmfnDW0Lu9hBXiEgkQFuFc3qA7616m8j4ZS6SJptDyUNpMLgAnB8B6+qjGgS+X86t0/imEs2CkLQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBWJoeQ9uhuewNZm4jweOGzJ/QYx2h5jpBrka0f1Bd5mTxcqB9J/IjkeCjK9Qo2wffQVLxa9jW9/Q8eqUdvqhbRluyQupvJeifs2B710nZgAEp5VcpaSJNhj4YQIaw640f5FLHu4Rt8POezHwvSuGedalFXsQO/PJV3IKg6OpNZyLhT2c0H2NqOHJmnV3ltU4jR2aVU/lWLCvH0Lzlb3R/NAUvqgvDTugUkt2WoV+7sw57rEhNI4r5v4FEd1cbSOFu2Xnfk2Upgz5wswdkF8faZQR4LyDj4ZlCD5RSjaHaMLXJe7CZU33zHwaUbig+fPW4JYrDq7HZHT7i2+KsNLMil\n-----END CERTIFICATE-----",
          "cipherKey": "bobcipherKey",
          "email": "bob@mail.com",
          "invitationID": "0x12233344de"
        },
        "pass": "invitation message",
        "signature": "337aa3432103290b30f579ba62c72a370277bcb23fb798609cfdcf0909698c431788324f8ecf55e6f8d16cf8b1e5ae8606a3de77d3506a7c08e02894d4c0ba8126e8b09c38d7fdb85de2586b2b43cc76580358ae985e129f1296c821e5ac4a22258ec5d90048cd02fc063440682d5572f918f6b2dbaf7dd55bab5d26edfb81ec33a1904c1288205f4d7a70d3737c62cdb0f0eaee7218a17a46e1f5d25af97bd1ce24a5138804dbd4c48453274c7e028e687f58ba95b76bb7d6d2d881a1563d6cd32f46939fed24c1dde760d7b4a70ec406fdcc2e34bb5bbc8415831423468cebed80dc1b5ba3c89740ef2fc18477c49e9d408869c0d1a8a21a4abf1c437f8473"
      },
      "type": "object",
      "properties": {
        "sender": {
          "description": "",
          "example": "alicia",
          "type": "string"
        },
        "message": {
          "$ref": "#/definitions/Message6"
        },
        "pass": {
          "description": "",
          "example": "invitation message",
          "type": "string"
        },
        "signature": {
          "description": "",
          "example": "337aa3432103290b30f579ba62c72a370277bcb23fb798609cfdcf0909698c431788324f8ecf55e6f8d16cf8b1e5ae8606a3de77d3506a7c08e02894d4c0ba8126e8b09c38d7fdb85de2586b2b43cc76580358ae985e129f1296c821e5ac4a22258ec5d90048cd02fc063440682d5572f918f6b2dbaf7dd55bab5d26edfb81ec33a1904c1288205f4d7a70d3737c62cdb0f0eaee7218a17a46e1f5d25af97bd1ce24a5138804dbd4c48453274c7e028e687f58ba95b76bb7d6d2d881a1563d6cd32f46939fed24c1dde760d7b4a70ec406fdcc2e34bb5bbc8415831423468cebed80dc1b5ba3c89740ef2fc18477c49e9d408869c0d1a8a21a4abf1c437f8473",
          "type": "string"
        }
      },
      "required": [
        "sender",
        "message",
        "pass",
        "signature"
      ]
    },
    "Message6": {
      "title": "Message6",
      "example": {
        "name": "bob",
        "address": "0xb12233344de2",
        "publicKey": "-----BEGIN CERTIFICATE-----\nMIIDPjCCAiYCCQDjPaj4hdeMFTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJlczELMAkGA1UECAwCbWExCzAJBgNVBAcMAm1hMQswCQYDVQQKDAJhbDELMAkGA1UECwwCYWwxCzAJBgNVBAMMAmFsMREwDwYJKoZIhvcNAQkBFgJhbDAeFw0xODA2MTkxNzE2NTFaFw0xOTA2MTkxNzE2NTFaMGExCzAJBgNVBAYTAmVzMQswCQYDVQQIDAJtYTELMAkGA1UEBwwCbWExCzAJBgNVBAoMAmFsMQswCQYDVQQLDAJhbDELMAkGA1UEAwwCYWwxETAPBgkqhkiG9w0BCQEWAmFsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwB7hN2IiIdkftt+oJvNzSpwH2RwzsEbknaqCH8/BRZWIoH/1d6vIFi0Uvi6eAuR1PhNBwlz6zRJ/I9zpxFReS3FEqCvdSH7jV11lize4c/mKJMMTYx5EnsjVznsX1pyAL3o2Lrv4FwxDQ1eEyRfW6oeldHtNq4W6a7IVThKblcFBSDqYEZd+0ivYI1ahlnSg/wOOXrxmCT+pnMVJy+KiYmg7uV7dxnA83gkRNzf1NCj7DndgoCwX4RdeHMx7w+qAig0bIelw9VQmfnDW0Lu9hBXiEgkQFuFc3qA7616m8j4ZS6SJptDyUNpMLgAnB8B6+qjGgS+X86t0/imEs2CkLQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBWJoeQ9uhuewNZm4jweOGzJ/QYx2h5jpBrka0f1Bd5mTxcqB9J/IjkeCjK9Qo2wffQVLxa9jW9/Q8eqUdvqhbRluyQupvJeifs2B710nZgAEp5VcpaSJNhj4YQIaw640f5FLHu4Rt8POezHwvSuGedalFXsQO/PJV3IKg6OpNZyLhT2c0H2NqOHJmnV3ltU4jR2aVU/lWLCvH0Lzlb3R/NAUvqgvDTugUkt2WoV+7sw57rEhNI4r5v4FEd1cbSOFu2Xnfk2Upgz5wswdkF8faZQR4LyDj4ZlCD5RSjaHaMLXJe7CZU33zHwaUbig+fPW4JYrDq7HZHT7i2+KsNLMil\n-----END CERTIFICATE-----",
        "cipherKey": "bobcipherKey",
        "email": "bob@mail.com",
        "invitationID": "0x12233344de"
      },
      "type": "object",
      "properties": {
        "name": {
          "description": "",
          "example": "bob",
          "type": "string"
        },
        "address": {
          "description": "",
          "example": "0xb12233344de2",
          "type": "string"
        },
        "publicKey": {
          "description": "",
          "example": "-----BEGIN CERTIFICATE-----\nMIIDPjCCAiYCCQDjPaj4hdeMFTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJlczELMAkGA1UECAwCbWExCzAJBgNVBAcMAm1hMQswCQYDVQQKDAJhbDELMAkGA1UECwwCYWwxCzAJBgNVBAMMAmFsMREwDwYJKoZIhvcNAQkBFgJhbDAeFw0xODA2MTkxNzE2NTFaFw0xOTA2MTkxNzE2NTFaMGExCzAJBgNVBAYTAmVzMQswCQYDVQQIDAJtYTELMAkGA1UEBwwCbWExCzAJBgNVBAoMAmFsMQswCQYDVQQLDAJhbDELMAkGA1UEAwwCYWwxETAPBgkqhkiG9w0BCQEWAmFsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwB7hN2IiIdkftt+oJvNzSpwH2RwzsEbknaqCH8/BRZWIoH/1d6vIFi0Uvi6eAuR1PhNBwlz6zRJ/I9zpxFReS3FEqCvdSH7jV11lize4c/mKJMMTYx5EnsjVznsX1pyAL3o2Lrv4FwxDQ1eEyRfW6oeldHtNq4W6a7IVThKblcFBSDqYEZd+0ivYI1ahlnSg/wOOXrxmCT+pnMVJy+KiYmg7uV7dxnA83gkRNzf1NCj7DndgoCwX4RdeHMx7w+qAig0bIelw9VQmfnDW0Lu9hBXiEgkQFuFc3qA7616m8j4ZS6SJptDyUNpMLgAnB8B6+qjGgS+X86t0/imEs2CkLQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBWJoeQ9uhuewNZm4jweOGzJ/QYx2h5jpBrka0f1Bd5mTxcqB9J/IjkeCjK9Qo2wffQVLxa9jW9/Q8eqUdvqhbRluyQupvJeifs2B710nZgAEp5VcpaSJNhj4YQIaw640f5FLHu4Rt8POezHwvSuGedalFXsQO/PJV3IKg6OpNZyLhT2c0H2NqOHJmnV3ltU4jR2aVU/lWLCvH0Lzlb3R/NAUvqgvDTugUkt2WoV+7sw57rEhNI4r5v4FEd1cbSOFu2Xnfk2Upgz5wswdkF8faZQR4LyDj4ZlCD5RSjaHaMLXJe7CZU33zHwaUbig+fPW4JYrDq7HZHT7i2+KsNLMil\n-----END CERTIFICATE-----",
          "type": "string"
        },
        "cipherKey": {
          "description": "",
          "example": "bobcipherKey",
          "type": "string"
        },
        "email": {
          "description": "",
          "example": "bob@mail.com",
          "type": "string"
        },
        "invitationID": {
          "description": "",
          "example": "0x12233344de",
          "type": "string"
        }
      },
      "required": [
        "name",
        "address",
        "publicKey",
        "cipherKey",
        "email",
        "invitationID"
      ]
    },
    "CreateAInvitationrequest": {
      "title": "create_a_invitationRequest",
      "example": {
        "address": "0x12233344de",
        "message": {
          "expirationDate": 1561050357,
          "pass": "invitation message",
          "enabled": "true",
          "invitationSender": "0x12233344de"
        },
        "signature": "828773912f75628279a0d2f7f197c7cd960d0286a7b663dc6837dede73e1e58b29a0317d14535a64976ea8ae8b8684598f597ff472667417105efc299488e623b200c8963471375572bdf51d4489df87443bfa018cb4d64a833ca67a5e431170bd4913e19c5645d595f0db0ee7a0813c7847871569d9a3680dfb0eb292581cad481e43c25be10997d9a45d300b7366e804807dd7962ee199a0c991fd227f34a6b0e9ba50ee6d543f88799900bcb6990e37d31ddb95605a79bba8b4f0c31f67a9052062c4296bdebf16cb14d18c116d04830512d535bbff315d72537916a25531552d18f9b99787aa2036b1e96046c4c05c4317b4690ede2bfcdf49fc22c96560"
      },
      "type": "object",
      "properties": {
        "address": {
          "description": "",
          "example": "0x12233344de",
          "type": "string"
        },
        "message": {
          "$ref": "#/definitions/Message"
        },
        "signature": {
          "description": "",
          "example": "828773912f75628279a0d2f7f197c7cd960d0286a7b663dc6837dede73e1e58b29a0317d14535a64976ea8ae8b8684598f597ff472667417105efc299488e623b200c8963471375572bdf51d4489df87443bfa018cb4d64a833ca67a5e431170bd4913e19c5645d595f0db0ee7a0813c7847871569d9a3680dfb0eb292581cad481e43c25be10997d9a45d300b7366e804807dd7962ee199a0c991fd227f34a6b0e9ba50ee6d543f88799900bcb6990e37d31ddb95605a79bba8b4f0c31f67a9052062c4296bdebf16cb14d18c116d04830512d535bbff315d72537916a25531552d18f9b99787aa2036b1e96046c4c05c4317b4690ede2bfcdf49fc22c96560",
          "type": "string"
        }
      },
      "required": [
        "address",
        "message",
        "signature"
      ]
    },
    "UpdateAInvitationrequest": {
      "title": "update_a_invitationRequest",
      "example": {
        "enabled": true,
        "_id": "5b2bba6a042ab5cb4c7aebfa",
        "expirationDate": 1561050357,
        "pass": "invitation message",
        "invitationSender": "0x12233344de",
        "__v": 0
      },
      "type": "object",
      "properties": {
        "enabled": {
          "description": "",
          "example": true,
          "type": "boolean"
        },
        "_id": {
          "description": "",
          "example": "5b2bba6a042ab5cb4c7aebfa",
          "type": "string"
        },
        "expirationDate": {
          "description": "",
          "example": 1561050357,
          "type": "integer",
          "format": "int32"
        },
        "pass": {
          "description": "",
          "example": "invitation message",
          "type": "string"
        },
        "invitationSender": {
          "description": "",
          "example": "0x12233344de",
          "type": "string"
        },
        "__v": {
          "description": "",
          "example": 0,
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "enabled",
        "_id",
        "expirationDate",
        "pass",
        "invitationSender",
        "__v"
      ]
    }
  }
}